instaounce/instaounce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', include('instaounceApp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaounce/instaounceApp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'instaounce'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.DeleteImageView.as_view(), name='delete'),
    path('upload/', views.UploadView.as_view(), name='upload'),
]

instaounce/instaounceApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Image(models.Model):
    name = models.CharField(max_length = 100)
    image = models.ImageField(upload_to = 'images/')
    likes = models.IntegerField(default=0)
    pubDate = models.DateTimeField(auto_now_add=True, editable=False)
    author = models.ForeignKey(
      User,
      on_delete=models.CASCADE
    )

    def get_absolute_url(self):
        return reverse('/')

instaounce/instaounceApp/forms.py
from django import forms

from .models import Image

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = [
            'name',
            'image',
        ]

instaounce/instaounceApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from django.views import generic
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

from .models import Image
from .forms import UploadImageForm


class SignupView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'instaounceApp/signup.html'
    success_url = '/'


class Login(LoginView):
    template_name = 'instaounceApp/login.html'


class IndexView(generic.ListView):
    template_name = 'instaounceApp/index.html'
    context_object_name = 'latest_image_list'

    def get_queryset(self):
        return Image.objects.order_by('-pubDate')


class ProfileView(generic.ListView):
    template_name = 'instaounceApp/profile.html'
    context_object_name = 'user_uploaded_images'

    def get_queryset(self):
        return Image.objects.filter(author=self.request.user)


class DetailView(generic.DetailView):
    model = Image
    template_name = 'instaounceApp/detail.html'


class UploadView(generic.CreateView):
    form_class = UploadImageForm
    template_name = 'instaounceApp/upload.html'
    model = Image
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeleteImageView(LoginRequiredMixin, generic.DeleteView):
    model = Image
    template_name = 'instaounceApp/deleteImage.html'
    success_url = '/profile/'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            return HttpResponseForbidden("Cannot delete other's posts")

instaounce/instaounceApp/templates/instaounceApp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include './navbar.html' %}
    <div class="container-fluid">{% block content %}{% endblock %}</div>
  </body>
</html>

instaounce/instaounceApp/templates/instaounceApp/deleteImage.html
{% extends "./base.html" %} {% block content %} {% if user == image.author%}
<h1>{{ image.name }}</h1>
<form method="POST">
  {% csrf_token %}
  <ul>
    <h2>posted by {{ image.author }}</h2>
    <img src="{{ image.image.url }}" alt="{{ image.name }}" />
  </ul>
  <p>Are you sure you want to delete this image?</p>

  <button type="submit" class="btn btn-danger">Delete</button>
</form>
{% else %}
<p>Please respect other users and do not attempt to delete their images</p>
{% endif %} {% endblock %}

instaounce/instaounceApp/templates/instaounceApp/detail.html
{% extends "./base.html" %} {% block content %}

<h1>{{ image.name }}</h1>

<ul>
  <h2>posted by {{ image.author }}</h2>
  <img src="{{ image.image.url }}" alt="{{ image.name }}" />
</ul>
{% if user ==  image.author%}
<a class="btn btn-danger" href="{% url 'instaounce:delete' image.id %}">
  Delete Image
</a>
{% endif %} {% endblock %}

instaounce/instaounceApp/templates/instaounceApp/index.html
{% extends "./base.html" %} {% block content %} {% if user.is_authenticated %}
<h2>Feed</h2>
{% if latest_image_list %}
<ul>
  {% for image in latest_image_list %}
  <a href="{% url 'instaounce:detail' image.id %}">
    <img src="{{ image.image.url }}" alt="{{ image.name }}" />
  </a>
  {% endfor %}
</ul>
{% else %}
<p>No images are available.</p>
{% endif %} {% else %}
<p>Please login before accessing page</p>
{% endif %} {% endblock %}

instaounce/instaounceApp/templates/instaounceApp/login.html
{% extends "./base.html" %} {% block content %} {% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %} {% if next %} {% if user.is_authenticated %}
<p>
  Your account doesn't have access to this page. To proceed, please login with
  an account that has access.
</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %} {% endif %}

<form method="post" action="{% url 'instaounce:login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>

  <input type="submit" value="login" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

instaounce/instaounceApp/templates/instaounceApp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'instaounce:index' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'instaounce:profile' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'instaounce:upload' %}">Upload</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'instaounce:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'instaounce:signup' %}">Create Account</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'instaounce:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

instaounce/instaounceApp/templates/instaounceApp/profile.html
{% extends "./base.html" %} {% block content %}

<h1>{{ user.get_username }}</h1>
{% if user_uploaded_images %}
<ul>
  {% for image in user_uploaded_images %}
  <a href="{% url 'instaounce:detail' image.id %}">
    <img src="{{ image.image.url }}" alt="{{ image.name }}" />
  </a>
  {% endfor %}
</ul>
{% else %}
<p>No images are available.</p>
{% endif %} {% endblock %}

instaounce/instaounceApp/templates/instaounceApp/signup.html
{% extends "./base.html" %} {% block content %}
<h2>Sign up</h2>
<form
  method="post"
  action="{% url 'instaounce:signup' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
</form>
{% endblock %}

instaounce/instaounceApp/templates/instaounceApp/upload.html
{% extends "./base.html" %} {% block content %}

<h1>Upload image</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form
  action="{% url 'instaounce:upload' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div>{{ form.name }}</div>
  <div>{{ form.image }}</div>
  <button type="submit">Upload</button>
</form>

{% endblock %}